name: Frontend CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          repository: laundry-santuy/laundry-santuy-frontend
          token: ${{ secrets.FRONTEND_REPO_TOKEN }}
          ref: main
          path: laundry-santuy-frontend
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: ./laundry-santuy-frontend
        run: npm ci
      - name: Lint
        working-directory: ./laundry-santuy-frontend
        run: npm run lint
      - name: Build frontend
        working-directory: ./laundry-santuy-frontend
        run: npm run build